Kernel360/KBE5_HALO_FE

src/features/admin/api/adminAuth.ts
src/features/admin/components/AdminSidebar.tsx
src/features/admin/pages/AdminMain.tsx
src/features/customer/api/customerAuth.ts
src/features/customer/components/CustomerHeader.tsx
src/features/customer/pages/CustomerLogin.tsx
src/features/customer/pages/CustomerMain.tsx
src/features/manager/api/managerAuth.ts
src/features/manager/components/ManagerSidebar.tsx
src/features/manager/pages/ManagerLogin.tsx
src/services/axios.ts
src/shared/utils/login.ts
src/shared/utils/logout.ts
src/shared/utils/reissueToken.ts
src/store/useAuthStore.ts
src/store/useUserStore.ts

feat: JWT 기반 인증 시스템 구축 (accessToken/refreshToken + 역할별 분리)

feat: JWT 기반 인증 시스템 구축 (accessToken/refreshToken + 역할별 분리)

---

.gitignore
index.html
package-lock.json
package.json
src/features/manager/pages/ManagerInquiries.tsx
src/features/manager/pages/ManagerReservations.tsx
src/features/manager/pages/ManagerSignup.tsx
src/router/index.tsx
src/shared/components/AddressSearch.tsx
src/store/useAddressStore.ts
src/vite-env.d.ts

- Google Maps JavaScript API 연동 및 주소 자동완성 기능 구현
- 주소 자동완성 입력창을 별도 컴포넌트(`AddressSearch`)로 분리
- Zustand를 활용해 위도/경도/도로명주소/상세주소 전역 상태 관리
- Google Material Symbols 아이콘 적용 및 색상 커스터마이징 (`text-white`,  활용)
---
- `AddressSearch` 컴포넌트나 Zustand 상태 구조에서 개선이 필요한 부분 있으면 편하게 피드백 주세요!
- Google Maps Autocomplete 사용 시 UX 개선 방식(Enter 키 차단, 알림 등)에 대한 의견도 환영입니다
---
- [Google Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/overview?hl=ko)
- [Google Places Autocomplete](https://developers.google.com/maps/documentation/javascript/places-autocomplete?hl=ko)
- [Material Symbols (Google Icons)](https://fonts.google.com/icons)
---
- Close #11

#11: 구글맵 API 및 Google Material Icons 적용

---

src/features/manager/api/managerInquiry.ts
src/features/manager/components/ManagerSidebar.tsx
src/features/manager/pages/ManagerInquiries.tsx
src/features/manager/pages/ManagerInquiryDetail.tsx
src/features/manager/pages/ManagerInquiryForm.tsx
src/features/manager/types/ManagerInquirylType.ts
src/index.css
src/router/index.tsx
src/shared/components/FileUploadSection.tsx
src/shared/utils/validation.ts

- 문의사항 목록 조회
- 문의사항 상세 조회
- 문의사항 등록
- 문의사항 수정
- 문의사항 삭제
- Close #9

feat: [매니저] 문의사항 관리 기능 개발 및 첨부파일 컴포넌트 생성

---

src/features/admin/api/adminAuth.ts
src/features/customer/api/customerAuth.ts
src/features/manager/api/managerAuth.ts
src/features/manager/api/managerInquiry.ts
src/features/manager/api/managerMy.ts
src/features/manager/api/managerReview.ts
src/features/manager/components/ManagerSidebar.tsx
src/features/manager/pages/ManagerInquiry/ManagerInquiryForm.tsx
src/features/manager/pages/ManagerLogin.tsx
src/features/manager/pages/ManagerMy/ManagerContractCancel.tsx
src/features/manager/pages/ManagerMy/ManagerMy.tsx
src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
src/features/manager/pages/ManagerSignup.tsx
src/features/manager/types/ManagerAuthType.ts
src/features/manager/types/ManagerMyType.ts
src/router/index.tsx
src/shared/components/AddressSearch.tsx
src/shared/components/FileUploadSection.tsx
src/shared/utils/login.ts
src/shared/utils/validation.ts
src/store/useAddressStore.ts
src/store/useUserStore.ts

- 회원가입 기능 구현
- 매니저 마이페이지
- 나의 정보 조회 기능 구현
- 나의 정보 수정 기능 구현
- 계약해지요청 기능 구현
- Close #34

#34: [매니저] 회원가입 및 마이페이지 기능 구현

---

src/features/customer/api/CustomerInquiries.ts
src/features/customer/api/customerAuth.ts
src/features/customer/components/CustomerHeader.tsx
src/features/customer/components/CustomerProfileCard.tsx
src/features/customer/components/CustomerSidebar.tsx
src/features/customer/layouts/CustomerLayout.tsx
src/features/customer/pages/customerInquiry/CustomerInquiryDetail.tsx
src/features/customer/pages/customerInquiry/CustomerInquiryForm.tsx
src/features/customer/pages/customerInquiry/CustomerInquiryPage.tsx
src/features/customer/types/CustomerInquiryType.ts
src/router/index.tsx
src/shared/utils/login.ts

- 수요자 문의사항 목록 조회
- 수요자 문의사항 수정/등록/삭제
- Header 이름 클릭시 마이페이지로 이동

feat : 수요자 문의사항 페이지 기능 구현

---

src/features/manager/components/ManagerSidebar.tsx
src/features/manager/layouts/ManagerLayout.tsx
src/features/manager/pages/ManagerInquiry/ManagerInquiries.tsx
src/features/manager/pages/ManagerInquiry/ManagerInquiryForm.tsx
src/features/manager/pages/ManagerLogin.tsx
src/features/manager/pages/ManagerMain.tsx
src/features/manager/pages/ManagerReservation/ManagerReservations.tsx
src/features/manager/pages/ManagerReview/ManagerReviews.tsx

- [매니저] sidebar 및 content 영역 UI 개선
- #49

#49: [매니저] sidebar 및 content 영역 UI 개선

---

src/features/admin/api/adminInquiry.ts
src/features/admin/pages/AdminInquiry/AdminInquiryDetail.tsx

- 문의자 정보 가져오는 변수 수정
- Close #47

문의자 정보 가져오는 변수 수정

---

src/features/customer/api/CustomerReservation.ts
src/features/customer/components/CustomerHeader.tsx
src/features/customer/components/ReservationCard.tsx
src/features/customer/pages/CustomerMain.tsx
src/features/customer/pages/reservation/CustomerMyReservationDetail.tsx
src/features/customer/pages/reservation/CustomerMyReservationPage.tsx
src/features/customer/types/CustomerReservationType.ts
src/router/index.tsx
src/shared/constants/ServiceIcons.ts
src/shared/utils/dateUtils.ts

1. 수요자 예약 목록 페이지 구현
2. 수요자 예약 상세 페이지 구현
3. Reservation Card 컴포넌트 생성
4. 날짜 format util 생성
5. 서비스 카테고리 이미지 constans 생성
6. 수요자 header, home nevigate 구현

[수요자] 나의 예약 페이지 구현

---

src/features/admin/components/AdminSidebar.tsx
src/features/customer/components/CustomerSidebar.tsx
src/features/manager/components/ManagerSidebar.tsx

- admin, customer, manager 페이지 사이드바 호버링 하이라이트 효과 수정
- Close #81

[공통]사이드바 호버링 하이라이트 변경

---

src/features/admin/components/AdminSidebar.tsx
src/features/admin/pages/AdminInquiry/AdminInquiries.tsx
src/features/admin/pages/AdminMain.tsx
src/features/admin/pages/AdminManager/AdminManagers.tsx

- 관리자 대시보드 화면 개발
- 매니저 신청 내역을 최근 3개를 확인할 수 있는 목록 추가
- 수요자, 매니저 문의사항 통합 목록에서 최근 3개를 확인할 수 있는 목록 추가
- 현재 매닞 신청자 수 표시
- 답변이 필요한 문의사항 수 표시
- Close #79

[관리자] 관리자 대시보드 화면 개발

---

src/features/manager/api/managerPayment.ts
src/features/manager/components/ManagerSidebar.tsx
src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
src/features/manager/types/ManagerPaymentType.ts
src/router/index.tsx

#88: [매니저] 정산관리 기능 구현

---

package.json

refactor: 의존성 수정

---

src/features/customer/api/CustomerReview.ts
src/features/customer/components/CustomerHeader.tsx
src/features/customer/pages/customerReview/CustomerReviewForm.tsx
src/features/customer/pages/customerReview/CustomerReviewsPage.tsx

---
- 수정 api와 리뷰 페이지 연결
---
Closes #132

[Refactor] 수요자 리뷰 페이지 api 연결

---

src/features/manager/api/managerMy.ts
src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
src/features/manager/pages/ManagerSignup.tsx

---
- ServiceCategoryTreeType import 경로 수정
---
- 빌드 오류 수정 했습니다.
---
Closes #130 #140 #144

[Fix] 빌드 애러 수정

---

src/features/customer/api/CustomerReservation.ts
src/features/customer/components/CustomerSidebar.tsx
src/features/customer/components/ManagerSelector.tsx
src/features/customer/components/ReservationCard.tsx
src/features/customer/components/ReservationStepIndicator.tsx
src/features/customer/components/ServiceTypeSelector.tsx
src/features/customer/modal/ReservationCancelModal.tsx
src/features/customer/pages/reservation/CustomerMyReservationDetail.tsx
src/features/customer/pages/reservation/CustomerMyReservationPage.tsx
src/features/customer/pages/reservation/ReservationRouteGuard.tsx
src/features/customer/pages/reservation/ReservationStepFinal.tsx
src/features/customer/pages/reservation/ReservationStepOne.tsx
src/features/customer/pages/reservation/ReservationStepTwo.tsx
src/features/customer/types/CustomerReservationType.ts
src/shared/components/ui/ProfileImagePreview.tsx
src/shared/ui/ReservationDateCalendar.tsx

---
- 예약 프로세스 페이지 UI/UX 개선
- 매니저 프로필 url 로 이미지 조회
- 반응형 페이지 추가
---
- /shared 경로에 ProfileImage추가하였습니다
- 해당 컴포넌트 사용하여 매니저 이미지 프로필 조회 가능합니다.
---
Closes #157

[Refactor] 예약페이지 개선

---

src/features/customer/components/CustomerFooter.tsx
src/features/customer/components/CustomerHeader.tsx
src/features/customer/modal/ServiceDetailModal.tsx
src/features/customer/pages/CustomerMain.tsx

- 헤더, 푸터, 홈페이지 개선
---
- 기능이 없는 하드코딩 부분 삭제
- 반응형 웹 구축 안되어있음
---
- 홈페이지 하드코딩 삭제
- 반응형 웹 구축
---
- 반응형 웹 확인
- 만들어 둔 버튼 실제 작동 확인
---

[Refactor] 헤더, 푸터, 홈페이지 개선 

---

src/features/customer/pages/CustomerMyInfo.tsx

- 수요자 마이페이지
---
- 디자인이 정돈되지 않음
- 포인트가 눈에 뜨지 않음
---
- 디자인 개선
- 개별 포인트 영역으로 개선
- 반응형 웹 구축
---
- 회원정보 수정 시 데이터 저장되는지 확인
- 반응형 웹 구축 확인
---
close #178

refactor : 수요자 마이페이지 개선

---

src/features/admin/pages/AdminAccount/AdminAccounts.tsx
src/features/customer/pages/CustomerLogin.tsx
src/features/customer/pages/CustomerSignup.tsx
src/features/manager/api/managerAuth.ts
src/features/manager/pages/ManagerSignup.tsx
src/features/manager/types/ManagerAuthType.ts
src/main.tsx
src/shared/components/OAuthFailPage.tsx
src/shared/components/OAuthProgressPage.tsx
src/shared/components/OAuthSuccessPage.tsx
src/shared/components/ui/LoginCard.tsx
src/shared/utils/login.ts
src/shared/utils/logout.ts

---
- 클라이언트에서 요청한 role과 백엔드에서 응답한 role이 다른 경우 로그인 실패로 처리
- 사용하지 않는 변수 제거
- 회원가입 요청시 중첩 파라미터 사용하지만 요청 파라미터 type에는 파라미터를 펼쳐놓은 오류 수정
---
- 페이지 권한 없는 사용자가 소셜 로그인 했을 때 로그인 실패가 되도록 수정했습니다.
---
Closes #160

[Fix] 빌드 오류 수정 및 페이지 권한 없는 사용자 로그인 가능 문제

---

src/features/admin/api/adminSettlement.ts
src/features/admin/components/AdminSidebar.tsx
src/features/admin/pages/AdminMain.tsx
src/features/admin/pages/AdminSettlement/AdminSettlements.tsx
src/features/admin/types/AdminPaymentType.ts
src/features/manager/api/managerPayment.ts
src/features/manager/components/KPISection.tsx
src/features/manager/components/ManagerSidebar.tsx
src/features/manager/components/TodayScheduleSection.tsx
src/features/manager/pages/ManagerMain.tsx
src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
src/features/manager/types/ManagerPaymentType.ts
src/router/index.tsx

---
- 매니저 정산 페이지 개발
- 관리자 정산 페이지 개발
- 매니저, 관리자 대시보드 정산 기능 연결
---
Closes #100

[Feature] 매니저, 관리자 정산 페이지 개발

---

src/features/customer/pages/reservation/CustomerMyReservationDetail.tsx

---
- 머지 중 빌드 에러 발생으로 수정
---
Closes #187

refactor: 빌드에러 수정

---

src/features/manager/components/CheckInOutCard.tsx
src/features/manager/components/KPISection.tsx
src/features/manager/components/ManagerReservationSearchForm.tsx
src/features/manager/components/ManagerReservationTable.tsx
src/features/manager/components/ReservationCheckInOutBanner.tsx
src/features/manager/pages/ManagerMy/ManagerMy.tsx
src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
src/features/manager/pages/ManagerReservation/ManagerReservations.tsx
src/features/manager/pages/ManagerReview/ManagerReviews.tsx
src/features/manager/types/ManagerMyType.ts
src/features/manager/types/ManagerReservationType.ts
src/shared/components/SearchForm.tsx

개선하고자 하는 코드/모듈/로직을 설명해주세요.
- 예약 상세페이지에 수요자 통계 정보 조회
- 대시보드 평균 별점 api 연결
- 리뷰 관리에 리뷰 개수, 평균 별점 조회
---
- 통계 관련 기능 부재로 매니저 로그인 시 확인 불가
---
- 예약 상세 페이지에서 수요자 통계 기능 추가
- 매니저 리뷰 관리 페이지에 매니저 통계 대시보드 추가
---
- 실제 데이터가 불러오는지 확인
---

[Refactor] 매니저 페이지 리펙토링

---

src/features/manager/pages/ManagerMy/ManagerMy.tsx
src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx

Refactor: 머지에러 해결

---

src/features/admin/components/AdminAccountForm.tsx
src/features/customer/components/CustomerFooter.tsx
src/router/index.tsx
src/shared/components/OAuthProgressPage.tsx
src/shared/components/PrivacyPolicyPage.tsx
src/shared/components/TermsOfServicePage.tsx

---
-  서비스 약관, 개인정보처리방침 페이지 추가
---
- 구글 로그인 앱 배포를 위한  서비스 약관, 개인정보처리방침 페이지 추가
---
Closes #182

[Refactor] 서비스 약관, 개인정보처리방침 페이지 추가

---

src/shared/components/OAuthProgressPage.tsx

---
- 소셜 로그인 신규 사용자 가입 오류 수정
---
- 소셜 로그인 신규 사용자 가입 오류 수정
---
Closes #182

[Fix] 소셜 로그인 신규 사용자 가입 오류 수정
